{"url": "https://api.github.com/repos/mozilla/node-firefox/issues/comments/72237372", "html_url": "https://github.com/mozilla/node-firefox/issues/20#issuecomment-72237372", "issue_url": "https://api.github.com/repos/mozilla/node-firefox/issues/20", "id": 72237372, "user": {"login": "sole", "id": 5609, "avatar_url": "https://avatars2.githubusercontent.com/u/5609?v=4", "gravatar_id": "", "url": "https://api.github.com/users/sole", "html_url": "https://github.com/sole", "followers_url": "https://api.github.com/users/sole/followers", "following_url": "https://api.github.com/users/sole/following{/other_user}", "gists_url": "https://api.github.com/users/sole/gists{/gist_id}", "starred_url": "https://api.github.com/users/sole/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/sole/subscriptions", "organizations_url": "https://api.github.com/users/sole/orgs", "repos_url": "https://api.github.com/users/sole/repos", "events_url": "https://api.github.com/users/sole/events{/privacy}", "received_events_url": "https://api.github.com/users/sole/received_events", "type": "User", "site_admin": false}, "created_at": "2015-01-30T17:26:29Z", "updated_at": "2015-01-30T17:26:29Z", "author_association": "MEMBER", "body_html": "<p>Yeah, I am using catch in places but the errors are not bubbling up often - because probably the chain of promises is not being returned. I am not sure that linting is going to solve this, it requires looking at the code by a human :-P</p>\n<p>Also, the second argument to <code>then</code> is not an exception but a <code>rejection</code> which should not throw.</p>", "body_text": "Yeah, I am using catch in places but the errors are not bubbling up often - because probably the chain of promises is not being returned. I am not sure that linting is going to solve this, it requires looking at the code by a human :-P\nAlso, the second argument to then is not an exception but a rejection which should not throw.", "body": "Yeah, I am using catch in places but the errors are not bubbling up often - because probably the chain of promises is not being returned. I am not sure that linting is going to solve this, it requires looking at the code by a human :-P\n\nAlso, the second argument to `then` is not an exception but a `rejection` which should not throw.\n"}